# Generated by Django 4.2.13 on 2024-06-03 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=10)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.assetcategory')),
            ],
        ),
    ]
